# Generated by Django 4.1.3 on 2022-11-17 00:35

import cmput404_project.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cmput404_project.storage_backends.MediaStorage(),
                upload_to="files/",
            ),
        ),
    ]
