# Generated by Django 4.1.3 on 2022-11-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboxitem",
            name="author",
        ),
        migrations.RemoveField(
            model_name="inboxitem",
            name="item_id",
        ),
        migrations.RemoveField(
            model_name="inboxitem",
            name="item_type",
        ),
        migrations.AddField(
            model_name="inboxitem",
            name="item",
            field=models.JSONField(default=dict),
        ),
    ]
