# Generated by Django 4.1.3 on 2022-11-19 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_inboxitem_author_remove_inboxitem_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post_id",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="liked_id",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
