# Generated by Django 3.1.14 on 2022-10-25 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20221023_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_id', models.UUIDField(editable=False)),
                ('is_comment', models.BooleanField(default=False)),
                ('accepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_accepter', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
