# Generated by Django 3.1.14 on 2022-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221023_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.UUIDField(editable=False),
        ),
    ]
