# Generated by Django 4.1.3 on 2022-11-19 02:30

import cmput404_project.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_id_alter_comment_post_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="accepter",
        ),
        migrations.RemoveField(
            model_name="like",
            name="liked_id",
        ),
        migrations.RemoveField(
            model_name="like",
            name="sender",
        ),
        migrations.AddField(
            model_name="like",
            name="author",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="like",
            name="object",
            field=models.CharField(blank=True, editable=False, max_length=400),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.CharField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.CharField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="inbox",
            name="id",
            field=models.UUIDField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="inboxitem",
            name="id",
            field=models.UUIDField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="id",
            field=models.CharField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
