# Generated by Django 3.1.14 on 2022-10-25 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
