# Generated by Django 3.1.14 on 2022-10-29 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_like_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[(posts.models.item_types['post'], 1), (posts.models.item_types['comment'], 2), (posts.models.item_types['like'], 3), (posts.models.item_types['follow'], 4), (posts.models.item_types['unfollow'], 5), (posts.models.item_types['friendrequest'], 6), (posts.models.item_types['friendrequestaccept'], 7), (posts.models.item_types['friendrequestreject'], 8)], max_length=20)),
                ('item_id', models.UUIDField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='posts.InboxItem')),
            ],
        ),
    ]
