# Generated by Django 3.1.14 on 2022-10-29 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221029_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
