# Generated by Django 3.1.14 on 2022-10-29 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20221029_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
