# Generated by Django 3.1.14 on 2022-10-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221029_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('COMMON_MARK', 'COMMON_MARK'), ('UTF_8', 'UTF_8'), ('BASE_64', 'BASE_64'), ('PNG_BASE_64', 'PNG_BASE_64'), ('JPEG_BASE_64', 'JPEG_BASE_64'), ('HTML', 'HTML')], max_length=500),
        ),
    ]
