# Generated by Django 3.1.14 on 2022-10-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221029_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.Like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
    ]
