# Generated by Django 4.1.3 on 2022-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_auto_20221029_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="contentType",
            field=models.CharField(
                choices=[
                    ("COMMON_MARK", "text/markdown"),
                    ("UTF_8", "text/plain"),
                    ("BASE_64", "application/base64"),
                    ("PNG_BASE_64", "image/png;base64"),
                    ("JPEG_BASE_64", "image/jpeg;base64"),
                    ("HTML", "text/html"),
                ],
                default="text/plain",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="contentType",
            field=models.CharField(
                choices=[
                    ("COMMON_MARK", "text/markdown"),
                    ("UTF_8", "text/plain"),
                    ("BASE_64", "application/base64"),
                    ("PNG_BASE_64", "image/png;base64"),
                    ("JPEG_BASE_64", "image/jpeg;base64"),
                    ("HTML", "text/html"),
                ],
                default="text/plain",
                max_length=500,
            ),
        ),
    ]
