# Generated by Django 4.1.3 on 2022-11-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0015_comment_contenttype_post_img_alter_post_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="img",
        ),
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, upload_to="files/"),
        ),
    ]
