# Generated by Django 4.1.3 on 2022-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="is_another_server",
            field=models.BooleanField(default=False),
        ),
    ]
