# Generated by Django 3.1.6 on 2022-10-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
