# Generated by Django 4.1.3 on 2022-11-19 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0003_author_is_another_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
