# Generated by Django 4.1.3 on 2022-11-19 02:30

import cmput404_project.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_like_accepter_remove_like_liked_id_and_more"),
        ("authors", "0004_alter_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.CharField(
                default=cmput404_project.utilities.gen_id,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to="posts.like"
            ),
        ),
    ]
