# Generated by Django 3.1.6 on 2022-10-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
