# Generated by Django 4.1.3 on 2022-11-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0005_alter_author_id_alter_author_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="proxy",
            field=models.BooleanField(default=False),
        ),
    ]
