# Generated by Django 3.1.14 on 2022-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes'),
        ('authors', '0006_author_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='liked',
            field=models.ManyToManyField(to='posts.Like'),
        ),
    ]
