# Generated by Django 3.1.14 on 2022-10-29 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_inboxitem_published'),
        ('authors', '0007_author_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='liked',
            field=models.ManyToManyField(blank=True, to='posts.Like'),
        ),
    ]
