# Generated by Django 4.1.3 on 2022-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0008_auto_20221029_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="host",
            field=models.TextField(
                default="http://localhost:8000", editable=False, max_length=500
            ),
        ),
    ]
