# Generated by Django 3.1.6 on 2022-10-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'accepter'), name='unique_friend_request_combination'),
        ),
    ]
