# Generated by Django 3.1.14 on 2022-10-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20221021_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'permissions': [('can_accept_friend_request', 'Can accept friend request'), ('can_reject_friend_request', 'Can reject friend request')]},
        ),
    ]
