# Generated by Django 4.1.3 on 2022-11-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0003_auto_20221025_2302"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendrequest",
            name="unique_friend_request_combination",
        ),
    ]
