# Generated by Django 4.1.3 on 2022-11-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="nickname",
            field=models.CharField(default="nickname", max_length=200),
        ),
    ]
